[package]
name = "input"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
