[package]
name = "cap-sn"
version = "0.18.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subjective-logic = { git = "https://github.com/shinomi-lab/subjective-logic.git", tag = "v0.9.1" }
approx = "0.5"
graph-lib = { git = "https://github.com/shinomi-lab/graph-lib.git", tag = "v0.4.2" }
rand = { version = "0.8", features = ["small_rng"] }
arrow = { version = "51.0", features = ["ipc_compression"] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.6"
toml = "0.8"
rand_distr = "0.4"
tracing = { version = "0.1", features = ["release_max_level_off"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-logfmt = "0.3"
num-traits = "0.2"
thiserror = "1.0"
either = "1.9"
anyhow = "1.0"
itertools = "0.12"
tokio = { version = "1.37", features = ["rt", "macros", "rt-multi-thread", "sync", "time"] }
parking_lot = "0.12"
num_cpus = "1.8"
indicatif = "0.17"
