[package]
name = "cap-sn"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subjective-logic = { git = "https://github.com/shinomi-lab/subjective-logic.git", tag = "v0.6.6" }
approx = "0.5"
once_cell = "1"
graph-lib = { git = "https://github.com/shinomi-lab/graph-lib.git", tag = "v0.2.5" }
rand = { version = "0.8", features = ["small_rng"] }
arrow2 = { version = "0.18", features = ["io_ipc", "io_ipc_compression"] }
