[package]
name = "cap-sn"
version = "0.10.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subjective-logic = { git = "https://github.com/shinomi-lab/subjective-logic.git", tag = "v0.8.2" }
approx = "0.5"
graph-lib = { git = "https://github.com/shinomi-lab/graph-lib.git", tag = "v0.4.2" }
rand = { version = "0.8", features = ["small_rng"] }
arrow2 = { version = "0.18", features = [
    "io_ipc",
    "io_ipc_compression",
    "io_ipc_write_async",
] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.6"
toml = "0.8"
rand_distr = "0.4"
log = { version = "0.4", features = ["release_max_level_off"] }
env_logger = "0.11"
num-traits = "0.2"
thiserror = "1.0"
either = "1.9"
rayon = "1.8"
anyhow = "1.0"