[package]
name = "social-dilemma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subjective-logic = { git = "https://github.com/shinomi-lab/subjective-logic.git", tag = "v0.1.3" }
