[package]
name = "cap-sn"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subjective-logic = { git = "https://github.com/shinomi-lab/subjective-logic.git", tag = "v0.6.8" }
approx = "0.5"
once_cell = "1"
graph-lib = { git = "https://github.com/shinomi-lab/graph-lib.git", tag = "v0.3.1" }
rand = { version = "0.8", features = ["small_rng"] }
arrow2 = { version = "0.18", features = [
    "io_ipc",
    "io_ipc_compression",
    "io_ipc_write_async",
] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand_distr = "0.4"
log = "0.4"
env_logger = "0.10"
