informing = "/home/e25m5333/cap-sn/v2/test_2/strategy/informing/case2o.toml"

[information]
misinfo = "/home/e25m5333/cap-sn/v2/test_2/strategy/information_opinion/a75_50.csv"
correction = "/home/e25m5333/cap-sn/v2/test_2/strategy/information_opinion/n95_95.csv"
observation = "/home/e25m5333/cap-sn/v2/test_2/strategy/information_opinion/a75_80.csv"
inhibition = "/home/e25m5333/cap-sn/optimize_test_wiki-vote/cmaes/csv/inhibition_trial_best.csv"
